### ISSUE TITLE
ArrayIndexOutOfBoundsException when runnig WEASEL

### ISSUE THREAD

**Issue by watanabe8760** [patrickzib/SFA#17]
When running WEASEL on time series data whose lengths vary, the following error occurs (not always, but sometimes).
```java
java.lang.ArrayIndexOutOfBoundsException: 47
	at sfa.timeseries.TimeSeries.calcIncrementalMeanStddev(TimeSeries.java:237)
	at sfa.transformation.MFT.transformWindowing(MFT.java:115)
	at sfa.transformation.SFA.transformWindowing(SFA.java:292)
	at sfa.transformation.SFA.transformWindowingInt(SFA.java:327)
	at sfa.transformation.WEASEL.createWords(WEASEL.java:122)
	at sfa.transformation.WEASEL.access$000(WEASEL.java:21)
	at sfa.transformation.WEASEL$1.run(WEASEL.java:96)
	at sfa.classification.ParallelFor$1.run(ParallelFor.java:31)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.ArrayIndexOutOfBoundsException: 47
	at sfa.timeseries.TimeSeries.calcIncrementalMeanStddev(TimeSeries.java:237)
	at sfa.transformation.MFT.transformWindowing(MFT.java:115)
	at sfa.transformation.SFA.transformWindowing(SFA.java:292)
	at sfa.transformation.SFA.transformWindowingInt(SFA.java:327)
	at sfa.transformation.WEASEL.createWords(WEASEL.java:122)
	at sfa.transformation.WEASEL.access$000(WEASEL.java:21)
	at sfa.transformation.WEASEL$1.run(WEASEL.java:96)
	at sfa.classification.ParallelFor$1.run(ParallelFor.java:31)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.NullPointerException
	at sfa.transformation.WEASEL.createBagOfPatterns(WEASEL.java:151)
	at sfa.classification.WEASELClassifier.predict(WEASELClassifier.java:125)
	at xxxx.execution.WEASELClassifierCrossValidator.main(WEASELClassifierCrossValidator.java:45)
```

The cause seems to be `windowSize` in `MFT` class, which is set from the length of first sample of `TimeSeries []` at the line 354 in `SFA` class.
```java
      if (this.transformation == null) {
        this.transformation = new MFT(samples[0].getLength(), normMean, this.lowerBounding, this.mftUseMaxOrMin);
      }
```
It should not assume that the length of first sample is the representative, should it?

**Comment by patrickzib** [comment]
Hi, 

thank you very much for pointing out this bug. is there any change, you could give me a dataset where WEASEL produces this error? I have tried to create a dataset with variable length but it does not generate this error.

Meanwhile I have added a check in TimeSeries.calcIncrementalMeanStddev but I don't think it does fix the issue.

`    if (this.transformation == null) {
        this.transformation = new MFT(samples[0].getLength(), normMean, this.lowerBounding, this.mftUseMaxOrMin);
      }`
Should not be called when using WEASEL (i.e. this.transformation should not me null).

**Comment by patrickzib** [comment]
I did add some test cases and some bug-fixes for variable length time series. 
can you check again?

**Comment by watanabe8760** [comment]
Thank you, Patrick. You saved my day.

**Comment by patrickzib** [comment]
You are welcome! thank you for pointing out the error.

Thank you. I have removed line 224...
