### ISSUE TITLE
TimeSeriesLoader.java exception

### ISSUE THREAD

**Issue by ugapark** [patrickzib/SFA#22]
I am not able to load any dataset (any type arff or csv). For example: TwoLeadECG dataset I got this exception. 

`Exception in thread "main" java.lang.NumberFormatException: For input string: "-0.04372,0.003764,0.039377,0.1106,0.18183,0.30054,0.24118,0.20557,0.16996,0.074989,0.063118,0.015635,-0.031849,-0.067461,-0.079332,-0.091203,-0.15056,-0.22178,-0.24552,-0.2574,-0.2574,-0.24552,-0.23365,-0.24552,-0.28114,-0.2574,-0.2574,0.039377,0.098731,-0.70849,-1.7769,-2.3585,-2.5366,-2.5841,-2.4298,-2.0974,-1.9905,-1.9193,-1.8125,-1.765,-1.5869,-1.2545,-0.87468,-0.57791,-0.3761,-0.15056,0.18183,0.46673,0.57357,0.66853,0.69227,0.69227,0.73976,0.7635,0.81098,0.8466,0.88221,0.95343,1.0009,1.0484,1.1078,1.1671,1.2383,1.2739,1.2858,1.3333,1.357,1.3333,1.2739,1.1909,1.0603,0.95343,0.81098,0.69227,0.57357,0.44299,0.33615,0.21744,0.14621,0.08686,0.027506,-0.008107,1"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at java.lang.Double.valueOf(Unknown Source)
	at sfa.timeseries.TimeSeriesLoader.loadDataset(TimeSeriesLoader.java:53)`

Am I missing something or there is a bug in the loader class? 
Thanks

**Comment by ugapark** [comment]
The class "TimeSeriesLoader" assumes specific format such as an input file with no commas, the first column is the label, ..).
