### ISSUE TITLE
Memory related errors when running UCR tests

### ISSUE THREAD

**Issue by TSeMDiD** [patrickzib/SFA#29]
I am getting errors on about 15 data sets out of 85 data sets of UCR archive. 
I run in ItelliJ IDEA with -Xmx2048m
For example:

Done reading from /home/p/augment/UCR_TS_Archive_2015/Phoneme/Phoneme_TEST samples 1896 queryLength 1024
Done reading from /home/p/augment/UCR_TS_Archive_2015/Phoneme/Phoneme_TRAIN samples 214 queryLength 1024
Exception in thread "main" com.carrotsearch.hppc.BufferAllocationException: Not enough memory to allocate buffers for rehashing: 65,536 -> 131,072
	at com.carrotsearch.hppc.IntIntHashMap.allocateBuffers(IntIntHashMap.java:1144)
	at com.carrotsearch.hppc.IntIntHashMap.allocateThenInsertThenRehash(IntIntHashMap.java:1169)
	at com.carrotsearch.hppc.IntIntHashMap.put(IntIntHashMap.java:177)
	at com.carrotsearch.hppc.IntIntHashMap.putOrAdd(IntIntHashMap.java:256)
	at sfa.transformation.WEASEL.createBagOfPatterns(WEASEL.java:164)
	at sfa.classification.WEASELClassifier.predict(WEASELClassifier.java:130)
	at sfa.classification.WEASELClassifier.score(WEASELClassifier.java:124)
	at sfa.classification.WEASELClassifier.eval(WEASELClassifier.java:95)
	at sfa.MyUCRmain.main(MyUCRmain.java:61)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by patrickzib** [comment]
I am afraid 2gb of ram will not be enough for all datasets. WEASEL uses a rich feature space with lots of features. I suppose, you should reserve something between 4-8gb to run all datasets. 

if 2gb is all you can provide, you could try uncommenting WEASEL's bigrams, this will reduce memory consumption a lot, in lines 161-164:
https://github.com/patrickzib/SFA/blob/df22b5c89dee47486a2d4f5c21ad9f93086881a3/src/main/java/sfa/transformation/WEASEL.java#L161
